#!/usr/bin/python
# encoding: utf-8
import pymysql
# 打开数据库连接
db = pymysql.connect("localhost",
                    "root",
                    "xpP@ssW0rd",
                    "wzjh" 
                    )
# 使用cursor()方法获取操作游标
cursor = db.cursor()
# SQL 查询语句
sql = "SELECT * FROM EMPLOYEE \
       WHERE INCOME > '%d'" % (1000)
try:
   # 执行SQL语句
   cursor.execute(sql)
   # 获取所有记录列表
   results = cursor.fetchall()
   
   #执行数据库遍历
   for row in results:
      fname = row[0]
      lname = row[1]
      age = row[2]
      sex = row[3]
      income = row[4]
      # 打印结果
      print "fname=%s,lname=%s,age=%d,sex=%s,income=%d" % \
             (fname, lname, age, sex, income )
except:
   print "Error: unable to fecth data"

import pandas as pd
columns=["FIRST_NAME", "LAST_NAME", "AGE", "SEX", "INCOME"]
df = pd.DataFrame(list(results),columns=columns)
df.head()
# 关闭数据库连接
df
db.close()
